# Generated by Django 2.2.5 on 2019-10-01 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyerdata',
            name='address',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='buyerdata',
            name='first_name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='buyerdata',
            name='last_name',
            field=models.CharField(max_length=300),
        ),
    ]
